version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  pre_build:
    commands:
      - mkdir .build
      - ls -al
      - cp -a ./.venv/Lib/site-packages/* ./.build
      - rm -r /.build/psycopg2
      - cp -a /aws-psycopg2 /.build/psycopg2
      - cp *.py /.build
      - zip -r9 lambda-package.zip /.build/*
      - rm -r .build
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket om-lambda-repo --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml