version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  pre_build:
    commands:
      - cd .venv/Lib/site-packages
      - zip -r9 ${OLDPWD}/lambda-package.zip .
      - cd ${OLDPWD}
      - zip -g lambda-package.zip aws-lambda.py
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket om-lambda-repo --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml