AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  OMVendorLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.7
      Handler: aws-lambda.lambda_handler
      CodeUri:
        Bucket: om-lambda-repo
        Key: lambda-package.zip
      Events:
        OMVendorApiResource:
          Type: Api
          Properties:
            Path: /om/vendors
            Method: get